### ISSUE TITLE
Project Language and Notebook in Chapter 1

### ISSUE THREAD

**Issue by srbhr** [rwbfd/ml-training-camp#1]
Hey there! 
Is this project going to be available in English as well? Likely the [draft](https://github.com/rwbfd/ml-training-camp/blob/main/chap01/chap01.pdf) from Chapter 1 is in Mandarin (I guess, totally have no idea! )
And about the Python and R Basics, can we split the two and make them in separate notebooks? 
I'd be happy to help. 

And yes, Maybe remove the (z-lilb) tag from the [Statistics book](https://github.com/rwbfd/ml-training-camp/blob/main/chap01/All%20of%20Statistics%20A%20Concise%20Course%20in%20Statistical%20Inference%20by%20Larry%20Wasserman%20(z-lib.org).pdf) that you shared? 

Thanks, 
Saurabh

**Comment by rwbfd** [comment]
@srbhr Yes. It is an online open course in English I give in Chinese. So first it is Chinese. Then there will be an English version. It will be updated almost week. You can see the notebook, is in English. But the slides is in Chinese. Which is a bit unfortunately, as I originally intend this to be an English course. 

This is the first of the three. The first is Tabular Data Mining and Deep Learning. The second is NLP. The last one is CV and RL with an Emphasize on Auto Driving. Please wait for everything.
