### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by ghost** [rwbfd/ml-training-camp#10]

**Comment by rwbfd** [comment]
Hi, what seems to be the problem?
Best Regards

*Ran (Lucien) Wang*
*CTO, Yanbei Tech Inc.*
*AI Lab Head Algorithm Scientist, WeCredo inc.*
*AI Lecturer, GeekGang Training Platform*
TEL: +86 13045175170
Wechat: ranwangmath
Email: ran.wang.math@gmail.com

**Comment by dave1dunn** [comment]
Sorry, there is no problem here at all. We just scheduled a meeting at the end of the February as I was willing to learn more on Machine Learning with you. I am the guy from the discord, if you remember.

**Comment by rwbfd** [comment]
Ok. I remember that. Let me get back to that tomorrow~

**Comment by dave1dunn** [comment]
My apology if you are busy and couldn't reply. If you are available some other day then please let me know.
